-- V3__seed_locations_data.sql
-- Nạp dữ liệu 63 tỉnh/thành phố với ID 

INSERT INTO locations (location_id, name, parent_id, type) VALUES
(29, 'Hà Nội', NULL, 'PROVINCE'),
(41, 'TP. Hồ Chí Minh', NULL, 'PROVINCE'),
(15, 'Hải Phòng', NULL, 'PROVINCE'),
(43, 'Đà Nẵng', NULL, 'PROVINCE'),
(65, 'Cần Thơ', NULL, 'PROVINCE'),
(23, 'Hà Giang', NULL, 'PROVINCE'),
(11, 'Cao Bằng', NULL, 'PROVINCE'),
(24, 'Lào Cai', NULL, 'PROVINCE'),
(25, 'Lai Châu', NULL, 'PROVINCE'),
(26, 'Sơn La', NULL, 'PROVINCE'),
(27, 'Điện Biên', NULL, 'PROVINCE'),
(21, 'Yên Bái', NULL, 'PROVINCE'),
(22, 'Tuyên Quang', NULL, 'PROVINCE'),
(12, 'Lạng Sơn', NULL, 'PROVINCE'),
(97, 'Bắc Kạn', NULL, 'PROVINCE'),
(20, 'Thái Nguyên', NULL, 'PROVINCE'),
(19, 'Phú Thọ', NULL, 'PROVINCE'),
(88, 'Vĩnh Phúc', NULL, 'PROVINCE'),
(99, 'Bắc Ninh', NULL, 'PROVINCE'),
(98, 'Bắc Giang', NULL, 'PROVINCE'),
(14, 'Quảng Ninh', NULL, 'PROVINCE'),
(28, 'Hòa Bình', NULL, 'PROVINCE'),
(89, 'Hưng Yên', NULL, 'PROVINCE'),
(34, 'Hải Dương', NULL, 'PROVINCE'),
(17, 'Thái Bình', NULL, 'PROVINCE'),
(90, 'Hà Nam', NULL, 'PROVINCE'),
(18, 'Nam Định', NULL, 'PROVINCE'),
(35, 'Ninh Bình', NULL, 'PROVINCE'),
(36, 'Thanh Hóa', NULL, 'PROVINCE'),
(37, 'Nghệ An', NULL, 'PROVINCE'),
(38, 'Hà Tĩnh', NULL, 'PROVINCE'),
(73, 'Quảng Bình', NULL, 'PROVINCE'),
(74, 'Quảng Trị', NULL, 'PROVINCE'),
(75, 'Thừa Thiên Huế', NULL, 'PROVINCE'),
(92, 'Quảng Nam', NULL, 'PROVINCE'),
(76, 'Quảng Ngãi', NULL, 'PROVINCE'),
(77, 'Bình Định', NULL, 'PROVINCE'),
(78, 'Phú Yên', NULL, 'PROVINCE'),
(79, 'Khánh Hòa', NULL, 'PROVINCE'),
(85, 'Ninh Thuận', NULL, 'PROVINCE'),
(86, 'Bình Thuận', NULL, 'PROVINCE'),
(82, 'Kon Tum', NULL, 'PROVINCE'),
(81, 'Gia Lai', NULL, 'PROVINCE'),
(47, 'Đắk Lắk', NULL, 'PROVINCE'),
(48, 'Đắk Nông', NULL, 'PROVINCE'),
(49, 'Lâm Đồng', NULL, 'PROVINCE'),
(93, 'Bình Phước', NULL, 'PROVINCE'),
(70, 'Tây Ninh', NULL, 'PROVINCE'),
(61, 'Bình Dương', NULL, 'PROVINCE'),
(39, 'Đồng Nai', NULL, 'PROVINCE'),
(72, 'Bà Rịa - Vũng Tàu', NULL, 'PROVINCE'),
(62, 'Long An', NULL, 'PROVINCE'),
(63, 'Tiền Giang', NULL, 'PROVINCE'),
(71, 'Bến Tre', NULL, 'PROVINCE'),
(84, 'Trà Vinh', NULL, 'PROVINCE'),
(64, 'Vĩnh Long', NULL, 'PROVINCE'),
(66, 'Đồng Tháp', NULL, 'PROVINCE'),
(67, 'An Giang', NULL, 'PROVINCE'),
(68, 'Kiên Giang', NULL, 'PROVINCE'),
(95, 'Hậu Giang', NULL, 'PROVINCE'),
(83, 'Sóc Trăng', NULL, 'PROVINCE'),
(94, 'Bạc Liêu', NULL, 'PROVINCE'),
(69, 'Cà Mau', NULL, 'PROVINCE');

-- Ví dụ nạp Quận/Huyện với parent_id đúng theo số của Tỉnh
-- Quận của Hà Nội (Hà Nội ID = 29)
INSERT INTO locations (name, parent_id, type) VALUES 
('Quận Hoàn Kiếm', 29, 'DISTRICT'),
('Quận Ba Đình', 29, 'DISTRICT'),
('Quận Đống Đa', 29, 'DISTRICT');

-- Quận của TP. Hồ Chí Minh (TP.HCM ID = 41)
INSERT INTO locations (name, parent_id, type) VALUES 
('Quận 1', 41, 'DISTRICT'),
('Quận 3', 41, 'DISTRICT'),
('Quận 7', 41, 'DISTRICT');
